import type { ProclubWorkflowTemplate } from './types'
import { action, wa, withPositions } from './helpers'

export const CAPTURE_TEMPLATES: ProclubWorkflowTemplate[] = [
  {
    proclubId: 'WP-1',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Requiere modelo Lead.',
    name: 'PROCLUB · Alta lead y grupo provisional',
    description: '[PROCLUB:WP-1] Formulario público y asignación por edad.',
    triggerType: 'LEAD_CREATED',
    defaultActive: false,
    steps: withPositions([action('ASSIGN_TEAM_BY_AGE', { minAge: 0, maxAge: 99, teamId: '' }, 'assign')]),
  },
  {
    proclubId: 'WP-2',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'LEAD_CREATED.',
    name: 'PROCLUB · Info inicial al lead',
    description: '[PROCLUB:WP-2] Horarios, cuotas, prueba.',
    triggerType: 'LEAD_CREATED',
    defaultActive: false,
    steps: withPositions([wa('Gracias por contactar. Info del club y propuesta de prueba.', 'info')]),
  },
  {
    proclubId: 'WP-3',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Aviso entrenador.',
    name: 'PROCLUB · Aviso entrenador (prueba)',
    description: '[PROCLUB:WP-3] Nuevo lead en grupo.',
    triggerType: 'LEAD_CREATED',
    defaultActive: false,
    steps: withPositions([
      action('SEND_WHATSAPP_TO_TEAM', { teamId: '', waMessage: 'Nueva prueba programada.' }, 'coach'),
    ]),
  },
  {
    proclubId: 'WP-4',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Recordatorio 5h antes.',
    name: 'PROCLUB · Confirmación prueba',
    description: '[PROCLUB:WP-4] Recordatorio previo a prueba.',
    triggerType: 'LEAD_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Recordatorio: prueba en breve. Confirma asistencia.', 'confirm')]),
  },
  {
    proclubId: 'WP-5',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Lista espera.',
    name: 'PROCLUB · Lista de espera',
    description: '[PROCLUB:WP-5] Aviso cuando hay hueco.',
    triggerType: 'LEAD_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Hay plaza disponible en el grupo. Contacta con el club.', 'waitlist')]),
  },
  {
    proclubId: 'WP-6',
    proclubArea: 'capture',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Seguimiento lead frío.',
    name: 'PROCLUB · Seguimiento lead frío',
    description: '[PROCLUB:WP-6] Recordatorios X y X+7 días.',
    triggerType: 'LEAD_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('¿Seguís interesados en unirse al club?', 'followup')]),
  },
]

export const SIGNUP_TEMPLATES: ProclubWorkflowTemplate[] = [
  {
    proclubId: 'WI-1',
    proclubArea: 'signup',
    proclubType: 'Auto',
    implementationStatus: 'ready',
    phase: 1,
    notes: 'Enlace inscripción.',
    name: 'PROCLUB · Formulario inscripción',
    description: '[PROCLUB:WI-1] Enviar enlace de alta.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: false,
    steps: withPositions([
      action('CREATE_SIGNUP_LINK', { maxUses: 1, expiresInDays: 14 }, 'link'),
      wa('Completa tu inscripción desde el enlace que te envía el club.', 'signup'),
    ]),
  },
  {
    proclubId: 'WI-2',
    proclubArea: 'signup',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Validación menor/tutor.',
    name: 'PROCLUB · Validación menor',
    description: '[PROCLUB:WI-2] Datos tutor obligatorios.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WI-3',
    proclubArea: 'signup',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Firmas documentos.',
    name: 'PROCLUB · Firmas documentos',
    description: '[PROCLUB:WI-3] Consentimientos.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Falta firmar documentación del club.', 'sign')]),
  },
  {
    proclubId: 'WI-4',
    proclubArea: 'signup',
    proclubType: 'Auto',
    implementationStatus: 'ready',
    phase: 1,
    notes: 'Bienvenida post-inscripción.',
    name: 'PROCLUB · Onboarding post-inscripción',
    description: '[PROCLUB:WI-4] Bienvenida y normas.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: true,
    steps: withPositions([
      wa('Bienvenido/a {memberName} al club. Revisa horarios en el panel.', 'welcome'),
    ]),
  },
]

export const CHURN_TEMPLATES: ProclubWorkflowTemplate[] = [
  {
    proclubId: 'WB-1',
    proclubArea: 'churn',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Solicitud baja admin.',
    name: 'PROCLUB · Solicitud de baja',
    description: '[PROCLUB:WB-1] Confirmar fecha efectiva.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WB-2',
    proclubArea: 'churn',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Cancelar cuotas futuras.',
    name: 'PROCLUB · Cancelar cuotas futuras',
    description: '[PROCLUB:WB-2] Tras baja efectiva.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: withPositions([action('SET_MEMBER_STATUS', { targetStatus: 'INACTIVE' }, 'inactive')]),
  },
  {
    proclubId: 'WB-3',
    proclubArea: 'churn',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Lista espera WP-5.',
    name: 'PROCLUB · Liberar plaza',
    description: '[PROCLUB:WB-3] Aviso lista espera.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: withPositions([wa('Se ha liberado una plaza. Contacta con el club si te interesa.', 'slot')]),
  },
  {
    proclubId: 'WB-4',
    proclubArea: 'churn',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Encuesta motivo.',
    name: 'PROCLUB · Cierre y encuesta',
    description: '[PROCLUB:WB-4] Despedida y feedback.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: withPositions([wa('Lamentamos tu baja. Gracias por formar parte del club.', 'bye')]),
  },
  {
    proclubId: 'WB-5',
    proclubArea: 'churn',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Campaña retorno.',
    name: 'PROCLUB · Campaña retorno',
    description: '[PROCLUB:WB-5] Contacto tras X meses.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('¿Te apetece volver al club esta temporada?', 'return')]),
  },
]
