import type { ProclubWorkflowTemplate } from './types'
import { action, wa, withPositions } from './helpers'

export const BILLING_TEMPLATES: ProclubWorkflowTemplate[] = [
  {
    proclubId: 'WC-1',
    proclubArea: 'billing',
    proclubType: 'Manual',
    implementationStatus: 'manual',
    phase: 1,
    notes: 'Configurar planes en panel Contabilidad.',
    name: 'PROCLUB · Catálogo de cuotas (manual)',
    description: '[PROCLUB:WC-1] No es workflow: configuración de planes.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-2',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 1,
    notes: 'CREATE_SUBSCRIPTION al alta.',
    name: 'PROCLUB · Asignación de cuotas',
    description: '[PROCLUB:WC-2] Cuotas al alta en grupo.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: false,
    steps: withPositions([action('CREATE_SUBSCRIPTION', { planId: '' }, 'sub')]),
  },
  {
    proclubId: 'WC-3',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 1,
    notes: 'Primer cobro + enlace.',
    name: 'PROCLUB · Primer cobro inscripción',
    description: '[PROCLUB:WC-3] Matrícula y primera cuota.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: false,
    steps: withPositions([
      action('SEND_PAYMENT_LINK', {}, 'link'),
      wa('Completa el pago de inscripción: {paymentUrl}', 'pay'),
    ]),
  },
  {
    proclubId: 'WC-4',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 1,
    notes: 'INVOICE_CREATED (cron billing).',
    name: 'PROCLUB · Cuotas periódicas',
    description: '[PROCLUB:WC-4] Emisión mensual.',
    triggerType: 'INVOICE_CREATED',
    defaultActive: false,
    steps: withPositions([
      action('SEND_PAYMENT_LINK', {}, 'link'),
      wa('Nueva cuota {invoiceNumber}. Pendiente: {pendingAmount} {invoiceCurrency}. {paymentUrl}', 'inv'),
    ]),
  },
  {
    proclubId: 'WC-5',
    proclubArea: 'billing',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Cobro extra manual.',
    name: 'PROCLUB · Concepto extra',
    description: '[PROCLUB:WC-5] Ropa, viaje, campus.',
    triggerType: 'INVOICE_CREATED',
    defaultActive: false,
    steps: withPositions([wa('Nuevo cobro: {invoiceNumber}. {paymentUrl}', 'extra')]),
  },
  {
    proclubId: 'WC-6',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Reglas descuento pendientes.',
    name: 'PROCLUB · Descuentos y becas',
    description: '[PROCLUB:WC-6] Aplicar descuentos automáticos.',
    triggerType: 'INVOICE_CREATED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-7',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'ready',
    phase: 1,
    notes: 'INVOICE_PAID + recibo PDF WhatsApp.',
    name: 'PROCLUB · Pago y recibo',
    description: '[PROCLUB:WC-7] Confirmación y PDF.',
    triggerType: 'INVOICE_PAID',
    defaultActive: true,
    steps: withPositions([
      action('SEND_INVOICE_PDF_WHATSAPP', { waMessage: 'Pago recibido. Adjuntamos factura {invoiceNumber}.' }, 'pdf'),
    ]),
  },
  {
    proclubId: 'WC-8',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'ready',
    phase: 1,
    notes: 'INVOICE_OVERDUE.',
    name: 'PROCLUB · Aviso impago',
    description: '[PROCLUB:WC-8] Primer aviso tras vencimiento.',
    triggerType: 'INVOICE_OVERDUE',
    defaultActive: true,
    steps: withPositions([
      wa('Cuota pendiente {invoiceNumber}: {pendingAmount} {invoiceCurrency}. Pagar: {paymentUrl}', 'due'),
    ]),
  },
  {
    proclubId: 'WC-9',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Reintento pasarela.',
    name: 'PROCLUB · Reintento cobro',
    description: '[PROCLUB:WC-9] Reintento tras fallo.',
    triggerType: 'INVOICE_OVERDUE',
    defaultActive: false,
    steps: withPositions([action('SEND_PAYMENT_LINK', {}, 'retry')]),
  },
  {
    proclubId: 'WC-10',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Alerta admin.',
    name: 'PROCLUB · Escalado impago',
    description: '[PROCLUB:WC-10] Notificar administración.',
    triggerType: 'INVOICE_OVERDUE',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-11',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Resumen semanal (job).',
    name: 'PROCLUB · Listado impagos',
    description: '[PROCLUB:WC-11] Informe periódico.',
    triggerType: 'INVOICE_OVERDUE',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-12',
    proclubArea: 'billing',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Suspender socio.',
    name: 'PROCLUB · Bloqueo por impago',
    description: '[PROCLUB:WC-12] Suspensión por morosidad.',
    triggerType: 'INVOICE_OVERDUE',
    defaultActive: false,
    steps: withPositions([action('SET_MEMBER_STATUS', { targetStatus: 'INACTIVE' }, 'suspend')]),
  },
  {
    proclubId: 'WC-13',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Tarjeta caducada Stripe.',
    name: 'PROCLUB · Tarjeta caducada',
    description: '[PROCLUB:WC-13] Actualizar método de pago.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Actualiza tu método de pago en el club.', 'card')]),
  },
  {
    proclubId: 'WC-14',
    proclubArea: 'billing',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Pausa cobros.',
    name: 'PROCLUB · Pausa de cobros',
    description: '[PROCLUB:WC-14] Lesión o suspensión temporal.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-15',
    proclubArea: 'billing',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Devolución prorrateada.',
    name: 'PROCLUB · Devolución prorrateada',
    description: '[PROCLUB:WC-15] Tras baja a mitad de mes.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-16',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Saldo a favor.',
    name: 'PROCLUB · Saldo a favor',
    description: '[PROCLUB:WC-16] Bono en próximo cobro.',
    triggerType: 'INVOICE_PAID',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WC-17',
    proclubArea: 'billing',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Renovación temporada.',
    name: 'PROCLUB · Renovación temporada',
    description: '[PROCLUB:WC-17] Propuesta nueva temporada.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Renovación de temporada disponible. Confirma en el panel del club.', 'renew')]),
  },
  {
    proclubId: 'WC-18',
    proclubArea: 'billing',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Export contable (job).',
    name: 'PROCLUB · Cierre contable',
    description: '[PROCLUB:WC-18] Export para gestoría.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: [],
  },
]
