import type { ProclubWorkflowTemplate } from './types'
import { action, wa, withPositions } from './helpers'

export const SPORT_TEMPLATES: ProclubWorkflowTemplate[] = [
  {
    proclubId: 'WD-1',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'ready',
    phase: 1,
    notes: 'Asignación por edad + WhatsApp.',
    name: 'PROCLUB · Alta en plantilla del grupo',
    description: '[PROCLUB:WD-1] Incorporar jugador al grupo y avisar al tutor.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: true,
    steps: withPositions([
      action('ASSIGN_TEAM_BY_AGE', { minAge: 0, maxAge: 99, teamId: '' }, 'assign'),
      wa('Hola, {memberName} ya está en {assignedTeamName}. Consulta horarios en el panel del club.', 'welcome'),
    ]),
  },
  {
    proclubId: 'WD-2',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Requiere TeamSchedule + GENERATE_TEAM_SESSIONS.',
    name: 'PROCLUB · Calendario recurrente',
    description: '[PROCLUB:WD-2] Sesiones desde horarios del grupo.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([action('GENERATE_TEAM_SESSIONS', { teamId: '' }, 'gen')]),
  },
  {
    proclubId: 'WD-3',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'EVENT_STARTING_SOON + aviso entrenador.',
    name: 'PROCLUB · Recordatorio pase de lista',
    description: '[PROCLUB:WD-3] WhatsApp al entrenador antes de la sesión.',
    triggerType: 'EVENT_STARTING_SOON',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WD-4',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'ATTENDANCE_ABSENT_UNEXCUSED.',
    name: 'PROCLUB · Falta no justificada',
    description: '[PROCLUB:WD-4] Aviso al tutor por ausencia.',
    triggerType: 'ATTENDANCE_ABSENT_UNEXCUSED',
    defaultActive: false,
    steps: withPositions([
      wa('Hola, {memberName} no asistió sin justificar. ¿Podéis indicar el motivo?', 'absence'),
    ]),
  },
  {
    proclubId: 'WD-5',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'EVENT_CANCELLED + SEND_WHATSAPP_TO_TEAM.',
    name: 'PROCLUB · Cancelación de sesión',
    description: '[PROCLUB:WD-5] Aviso a toda la plantilla.',
    triggerType: 'EVENT_CANCELLED',
    defaultActive: false,
    steps: withPositions([
      action('SEND_WHATSAPP_TO_TEAM', { teamId: '', waMessage: 'Sesión cancelada o reprogramada. Revisad el calendario.' }, 'notify'),
    ]),
  },
  {
    proclubId: 'WD-6',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Asignación sustituto manual.',
    name: 'PROCLUB · Sustitución entrenador',
    description: '[PROCLUB:WD-6] Aviso de cambio de entrenador.',
    triggerType: 'EVENT_RESCHEDULED',
    defaultActive: false,
    steps: withPositions([wa('Cambio de entrenador en la sesión. Revisad el calendario.', 'sub')]),
  },
  {
    proclubId: 'WD-7',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Modelo convocatoria pendiente.',
    name: 'PROCLUB · Convocatoria partido',
    description: '[PROCLUB:WD-7] Convocatoria y recordatorios.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WD-8',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'No convocados.',
    name: 'PROCLUB · No convocado',
    description: '[PROCLUB:WD-8] Aviso a jugadores fuera de convocatoria.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('No estás convocado/a al partido de esta jornada.', 'not_called')]),
  },
  {
    proclubId: 'WD-9',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'EVENT_COMPLETED.',
    name: 'PROCLUB · Resultado partido',
    description: '[PROCLUB:WD-9] Recordatorio resultado al entrenador.',
    triggerType: 'EVENT_COMPLETED',
    defaultActive: false,
    steps: [],
  },
  {
    proclubId: 'WD-10',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Cambio grupo + cuotas.',
    name: 'PROCLUB · Cambio de grupo',
    description: '[PROCLUB:WD-10] Baja en grupo actual y alta en nuevo.',
    triggerType: 'MEMBER_STATUS_CHANGED',
    defaultActive: false,
    steps: withPositions([
      action('REMOVE_FROM_TEAM', { teamId: '' }, 'remove'),
      action('ASSIGN_TEAM', { teamId: '' }, 'assign'),
      wa('Cambio de grupo: ahora {assignedTeamName}.', 'change'),
    ]),
  },
  {
    proclubId: 'WD-11',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Evaluación trimestral.',
    name: 'PROCLUB · Evaluación al tutor',
    description: '[PROCLUB:WD-11] Enviar evaluación cerrada.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([wa('Evaluación de {memberName} disponible. Contacta con el entrenador si tienes dudas.', 'eval')]),
  },
  {
    proclubId: 'WD-12',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'DOCUMENT_EXPIRING.',
    name: 'PROCLUB · Vencimiento documentación',
    description: '[PROCLUB:WD-12] Licencia, médico o seguro.',
    triggerType: 'DOCUMENT_EXPIRING',
    defaultActive: false,
    steps: withPositions([wa('Documentación de {memberName} próxima a vencer. Renovávela cuanto antes.', 'doc')]),
  },
  {
    proclubId: 'WD-13',
    proclubArea: 'sport',
    proclubType: 'Auto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'SEND_WHATSAPP_TO_TEAM.',
    name: 'PROCLUB · Comunicación masiva',
    description: '[PROCLUB:WD-13] Mensaje al grupo.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: withPositions([
      action('SEND_WHATSAPP_TO_TEAM', { teamId: '', waMessage: 'Aviso del club.' }, 'broadcast'),
    ]),
  },
  {
    proclubId: 'WD-14',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 2,
    notes: 'Onboarding entrenador.',
    name: 'PROCLUB · Onboarding entrenador',
    description: '[PROCLUB:WD-14] Bienvenida al entrenador del grupo.',
    triggerType: 'MEMBER_CREATED',
    defaultActive: false,
    steps: withPositions([wa('Bienvenido/a. Revisa plantilla y calendario en el CRM.', 'coach')]),
  },
  {
    proclubId: 'WD-15',
    proclubArea: 'sport',
    proclubType: 'Mixto',
    implementationStatus: 'partial',
    phase: 3,
    notes: 'Buzón incidencias pendiente.',
    name: 'PROCLUB · Incidencias entrenador',
    description: '[PROCLUB:WD-15] Seguimiento de incidencia.',
    triggerType: 'MEMBER_UPDATED',
    defaultActive: false,
    steps: [],
  },
]
